//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloClient.HelloDOB {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloDOB.DOBSoap")]
    public interface DOBSoap {
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDob", ReplyAction="*")]
        HelloClient.HelloDOB.GetDobResponse GetDob(HelloClient.HelloDOB.GetDobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDob", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloClient.HelloDOB.GetDobResponse> GetDobAsync(HelloClient.HelloDOB.GetDobRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDobRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDob", Namespace="http://tempuri.org/", Order=0)]
        public HelloClient.HelloDOB.GetDobRequestBody Body;
        
        public GetDobRequest() {
        }
        
        public GetDobRequest(HelloClient.HelloDOB.GetDobRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDobRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        public GetDobRequestBody() {
        }
        
        public GetDobRequestBody(string date) {
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDobResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDobResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelloClient.HelloDOB.GetDobResponseBody Body;
        
        public GetDobResponse() {
        }
        
        public GetDobResponse(HelloClient.HelloDOB.GetDobResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDobResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDobResult;
        
        public GetDobResponseBody() {
        }
        
        public GetDobResponseBody(string GetDobResult) {
            this.GetDobResult = GetDobResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DOBSoapChannel : HelloClient.HelloDOB.DOBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DOBSoapClient : System.ServiceModel.ClientBase<HelloClient.HelloDOB.DOBSoap>, HelloClient.HelloDOB.DOBSoap {
        
        public DOBSoapClient() {
        }
        
        public DOBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DOBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloClient.HelloDOB.GetDobResponse HelloClient.HelloDOB.DOBSoap.GetDob(HelloClient.HelloDOB.GetDobRequest request) {
            return base.Channel.GetDob(request);
        }
        
        public string GetDob(string date) {
            HelloClient.HelloDOB.GetDobRequest inValue = new HelloClient.HelloDOB.GetDobRequest();
            inValue.Body = new HelloClient.HelloDOB.GetDobRequestBody();
            inValue.Body.date = date;
            HelloClient.HelloDOB.GetDobResponse retVal = ((HelloClient.HelloDOB.DOBSoap)(this)).GetDob(inValue);
            return retVal.Body.GetDobResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloClient.HelloDOB.GetDobResponse> HelloClient.HelloDOB.DOBSoap.GetDobAsync(HelloClient.HelloDOB.GetDobRequest request) {
            return base.Channel.GetDobAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelloClient.HelloDOB.GetDobResponse> GetDobAsync(string date) {
            HelloClient.HelloDOB.GetDobRequest inValue = new HelloClient.HelloDOB.GetDobRequest();
            inValue.Body = new HelloClient.HelloDOB.GetDobRequestBody();
            inValue.Body.date = date;
            return ((HelloClient.HelloDOB.DOBSoap)(this)).GetDobAsync(inValue);
        }
    }
}
